js/api.js
While trying to get a demo plugin working that sends a message from Caret to an external plugin, I could only get Caret to send an empty object. So I went into api.json and made a couple small changes. I got rid of the `Object.create` line where the message variable is created, and replaced the single usage of the message variable with `config.message`. This makes Caret send the object specified in the External Commands file properly, rather than sending an empty one.
Here is the demo plugin I've created which will work with these changes: https://github.com/pigeontech/CaretPluginDemo
=> Changed message object

js/sessions/autosave.js
NB - made the change in Caret, it removed the trailing spaces
=> Fix #364 - autosave only saves changed tabs

config/ace.json, manifest.json
It looks like this one line is all that's needed to enable JSX support for all those devs using React.
The syntax highlighting is more visible in some themes than others (compare chrome to monokai), but it definitely seems to work.
=> Enabled JSX support

css/dialog.less
I settled for Material blue-grey 700. Here's how it looks:
=> Blue-grey links and buttons in dialogs (fixes #427)

config/ace.json
Add file extensions to the powershell mode in `ace.json` to be up-to-date with current powershell file types and DSC `mof` files.  
The `clixml`, `psc1`, and `pssc` powershell extensions are less-used but the `ps*1*` file extensions are extremely common.  See [here](https://en.wikipedia.org/wiki/Windows_PowerShell#File_extensions) for the extensions as listed on wiki.
This is a duplicate of `Add Powershell file extensions to ace.json #433` which I could not properly update due to my own lack of expertise. I apologize for the inconvenience.
=> Add Powershell file extensions

config/ace.json
Arduino's language is basically just a subset of C++. I don't think it needs it's own mode, but this will at least save us from changing the syntax every time we open a .ino file.
=> Recognize Arduino files (extension .ino) as C++

config/ace.json
Syntax highlighting for [Maze](http://esolangs.org/wiki/Maze) has been added into Ace.
No need to merge until a new version of Ace has been released and merged into Caret.
=> Add maze mode to ace config

js/sessions/switching.js, js/tab.js, js/ui/projectManager.js, js/ui/searchbar.js
These are the changes I made when making search results clickable, other than the parts that make search results clickable. You will more than likely want them in the implementation that you go with.
Adds:
* Read-only search tabs
* Bug fix: making search results stop exactly on limit
* Optional callback from project.openFile
* Restructure searchbar.js to be a little more organized with less duplicate code
=> Read-only search tabs, cb() from openFile, bug fix

config/ace.json, manifest.json
<a href="https://magento.com/">Magento</a> uses files with a .phtml extension, and these weren't included in the syntax highlighting. I added them to the PHP mode since they often contain quite a bit of it.
=> Added phtml files to use PHP syntax highlighting

css/searchbar.less, js/ui/searchbar.js
Fixes #467 using the cloud9 search results ace mode, with a minor alteration to Caret's search results output.
Also adds highlighting for the search term in the search results.
=> Add search results highlighting

config/user.json, js/editor.js
This enables live autocompletion via user setting `autocompleteLive` (means that auto complete window will appear automatically as the user is typing instead of having to press _ctrl+space_)
The feature is already present in Ace editor, so just giving an ability to enable it via config.
=> Feature / enable editor live autocomplete

config/api.json
chrome.runtime.sendMessageExternal is outdated, and has been replaced be chrome.runtime.sendMessage
Addresses issue #635 
(unsure if this is the only place it's used, however I can only assume it is)
=> Changed sendMessageExternal to sendMessage

config/ace.json
Currently, .vue files (used for Vue.js components) do not have syntax highlighting. After doing some research (https://github.com/ajaxorg/ace/issues/2841), it seems like the consensus is to use HTML syntax highlighting.
=> Support simple syntax highlighting for .vue files

config/ace.json
I do all of the development work for [Dirobium](https://github.com/Ewpratten/Dirobium) and the [Dirobium assembler](https://github.com/Ewpratten/DirAS) in caret, and was disappointed that there was no syntax highlighting for my .das files. It turns out that using the x86 syntax highlighting looks great for das too, so here is my little pull request to add some color to .das files.
=> Add support for dirobium assembly files

js/fileManager.js
I did something dumb today and accidentally reverted a file, losing all my changes. I was dismayed to find that there was no way to get my changes back! So here's a simple pull request :)
[Looking at ace docs](https://ace.c9.io/#nav=howto&api=edit_session), using session.setValue() resets undo history, but editor.setValue() preserves history so that Undo will undo the revert. 
Tested and working on a local build.
=> Enable Undo of File->Revert

js/sessions/binding.js
Allows an easy way to get the currently open tabs location, which can then be used elsewhere, eg. in the terminal to delete the file, create a sibling file, etc.
=> Provide option to copy file path in tab context menu

_locales/en/messages.json, js/sessions/binding.js, js/ui/projectManager.js
Adds a new option in the tab context menu to reveal the file in the side bar. This is achieved by traversing the directories tree, generating the list of directories above the selected file and adding these to the `expanded` hash. The side bar is then re-rendered. 
New context menu option | After option selection
--- | ---
=> Provide option to reveal in sidebar in tab context menu

js/storage/file.js
Handles the case where the file no longer exists
when opening the app and restoring files.  E.g. file
may be from a removable device.
=> Handle error in FileSystemFileEntry.file when reading

config/user.json
This is a very very small PR but hopefully it will save someone else some time.
I found that after changing the `jsHint` options in `user.json`, I had to restart the editor (which I didn't have to do for any of the other config options in `user.json`). It took me twenty minutes to figure this out, so I added a comment in `user.json` warning users to restart the editor after changing the jsHint options:
//jsHint settings are applied on opening a JS file. You may need to restart Caret for changes to take effect.
Thanks for the awesome editor, by the way! I've been looking for something like this for a very long time. I hope to contribute more in the future!
=> Add "you may need to restart" message to user.json

js/api.js
* As operator precedence, "!id in targets" means "(!id) in targets"
* refs : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* Fixed to "!( id in targets )"
=> Fixed the misused negation operator.

_locales/de/messages.json, config/ace.json
TSX is available in Ace, but was not enabled. I enabled it and fixed a small error in the de locale that was preventing loading the extension (bad json, was missing a comma).
=> Enable TSX language mode

config/ace.json
Both .nim and .nims file formats were not included in Caret, but are supported by Ace so I added both of them.
=> Added .nim syntax
